function casaSimpsons() {
    alert("Casa de los Simpsons \n \n742 de Evergreen Terrace es el domicilio ficticio donde vive la Familia Simpson, protagonista de la serie de televisión de dibujos animados Los Simpson. Está situado en la ciudad ficticia de Springfield, cuya localización es imposible de descubrir dado que durante la serie se hacen referencias contradictorias. Al igual que la ciudad, al domicilio de los Simpson también se le ha desubicado en varios capítulos cambiando el número de la casa en algunos capítulos: 59 (Mr. Lisa Goes to Washington), 94 (Blood Feud y Bart, el amante), 723 (Homer the Vigilante), 743 (Beyond Blunderdome), 1094 (New Kid on the Block), Matt Groening se le ocurrió la idea de poner este nombre por la calle donde él vivió de niño o también por la universidad a la que acudió desde 1972 hasta 1977, la universidad Evergreen State de Olympia, Washington.");
  }

function casaFlanders() {
    alert("Casa de los Flanders \n \nEl 744 de Evergreen Terrace (en Hispanoamérica traducido como Avenida Siempreviva 744) es la casa ficticia donde vive la Familia Flanders, vecinos de la familia Simpson. En ella viven Ned Flanders, Todd Flanders, Rod Flanders y anteriormente Maude Flanders. En el episodio 'Hurricane Neddy' la casa sufrió grandes daños luego de que un huracán pase sobre ella. Despues de pasar mucho tiempo desde la muerte de Maude Flanders , Ned Flanders se caso con Edna Krabappel, por lo que ella vivirá junto a él y con sus hijos en esta casa");
  }

function casaBurns() {
    alert("Casa del Sr Burns \n \nLa Mansión Burns es la gran mansión donde vive Charles Montgomery Burns. Tiene una cocina llena de cosas donde Smithers prepara las comidas del Sr. Burns excepto las comidas chatarras que no le gustan al Sr. Burns. La casa cuenta con tres niveles, que incluyen 200 habitaciones por cada uno, un ático, y un sótano en el primer piso. Una de las habitciones es la que ocupo Barta cuando fue momentariamente su heredero que tiene un tren que tarda un vuen rato en volver y llega con nieve. La habitación en la que duerme cuenta con un baño propio. Arriba es donde dormía su hijo Larry Burns. Tiene una hermosa biblioteca en la plata alta, la casa está decorada con muchos cuadros y antiguedades. Posee una habitación especial donde se encuentran monumentos de sus antepasados, junto con un monumento especial en el que estaba una copia del único billete de Un Trillón de Dólares. Tiene un hermoso y extenso jardín, con una antigua fuente al frente de la casa, y un ajedrez humano atrás, donde antes había una cancha de tenis. En el jardín se avistan muchos pavos reales. También se encuentra en el exterior una jaula donde se encuentran los perros guardianes, que son soltados bajo la orden de Burns, y la supervisón de Smithers.");
  }

function badulaque() {
    alert("El Badulaque \n \nEl Kwik-E-Mart, El Badulaque en España es un minisupermercado ubicado en Springfield visto recurrentemente en los episodios. Su dueño y principal vendedor es Apu Nahasapeemapetilon, quién dedica casi la totalidad de su tiempo al minisuper generando problemas con su familia y en especial con su esposa Manjula. Cuando Apu no se puede encargar de atender la tienda deja a cargo a su hermano Sanjay. Algunos empleados del minisuper han sido Jeremy Freedman, quien ha trabajado en muchísimos establecimientos más, Homer Simpson, un mono que compró para ayudarlo, sus hijos (en el futuro), entre otros.");
  }

function tiendaComics() {
    alert("La marmorra del Android \n \nEs la tienda de cómics y tarjetas de beisbol donde trabaja Jeff Albertson. Se supone que es la única tienda de revistas cómicas en todo Springfield. En ella no sólo se exhiben revistas cómicas sino también piezas únicas como primeras ediciones de series famosas y merchandising de colección. En varias oportunidades se hicieron convenciones de cómics, como por ejemplo cuando Homer iba a interpretar el papel de Poochie en la serie Itchy and Scratchy, se reunieron fanáticos y tanto Homer como la intérprete de las voces de Itchy y Scratchy respondían a sus preguntas.En el episodio Worst Episode Ever Jeff Albertson sufre un episodio cardíaco y Bart y Milhouse se quedan a cargo de la tienda por un tiempo. En el capítulo I Am Furious Yellow, Stan Lee pasó varios días en la tienda ayudando (o molestando) a los clientes. Bob Terwilliger, Nelson Muntz, George Lucas y Matt Groening tienen prohibida la entrada.");
  }

function ayuntamiento() {
    alert("Ayuntamiento \n \nEl Ayutamiento de Springfield fue visto durante varios episodios de la serie, es utilizado para debatir sobre variados temas relacionados con ideas nuevas para solucionar problemas, como pasó en el episodio 'Marge vs. the Monorail' que discutieron sobre el uso que tendría el dinero del Sr. Burns.");
  }

function colegio() {
    alert("Colegio de primaria de Springfield \n \nEs un colegio que aparece en la serie. Es la escuela a la cual asisten Bart Simpson, Lisa Simpson, Milhouse Van Houten, Martin Prince, Nelson Muntz, Ralph Wiggum, entre otros. Sus cursos abarcan desde el Jardín de Niños hasta el 6º Grado. La mascota escolar es el puma. La escuela se caracteriza por la mala calidad de enseñanza de los profesores, los cuales, por lo general, asisten desanimados a clase y no se preocupan si los alumnos están aprendiendo. Por mucho lo que hacen si se comportan mal es enviarlos junto al Director Skinner para que éste les imparta algún castigo. En Lisa Gets an 'A' el Superintendente Chalmers menciona que la escuela era la más destruida de Missouri y que por eso la habían desarmado ladrillo a ladrillo y trasladado a Springfield. Durante ese mismo episodio se ve como la escuela tiene varias ventanas rotas, no tiene salón de computadoras, y en el patio casi no hay juegos y los pocos que hay son peligrosos. Uno de los principales problemas de la escuela es que no recibe subsidios debido a las bajas calificaciones de los alumnos. Springfield, es una ciudad buenísima que nos aporta aprender cosas que nunca habiamos aprendido.");
  }

function bolera() {
    alert("Barney's Bowl-A-Rama \n \n'La Bolera de Barney' es una bolera de la ciudad de Springfield. Lo que hace estupendo este lugar no son sus aros de cebolla refritos 3 veces sino los fabulosos callejones de madera pulida que incluso un niño con el menor esfuerso puede hacer que la bola vaya a una velocidad lo suficiente para tirar un par de bolos. Aquí Homer Simpsons gano el campeonato, teniendo este como una gran azaña durante toda la serie");
  }

function iglesia() {
    alert("La Primera Iglesia de Springfield \n \nEs el lugar donde la mayoría de los ciudadanos de Springfield concurren todos los domingos para escuchar la palabra de Dios por boca del Reverendo Lovejoy apareció originalmente en uno de los cortos de Los Simpson emitidos en el Show de Tracey Ullman llamado 'Los Paganos'. El Reverendo Lovejoy dirige los destinos espirituales de toda la comunidad que profesa la religión protestante. Los discursos del reverendo suelen ser largos y aburridos lo que ha ocasionado que en varias ocasiones Bart haya puesto su nota de color con alguna gamberrada como por ejemplo cambiar las santas partituras musicales de la pianista por unas no tan santas. Y así como Bart, muchas veces los extenuados ciudadanos de Springfield buscan una manera de interrumpir los extensos discursos de Alegría para poder irse a sus casas a disfrutar del resto del domingo. La Iglesia de Springfield suele ser también el epicentro de los chismes de esa ciudad ya que las confesiones son oídas por otras personas además del Reverendo Lovejoy y esto hace que al poco tiempo todos sus habitantes estén al tanto de los pecados de sus vecinos.");
  }
